#!/usr/bin/env bash
#Install and configure HAproxy

sudo apt-get update
sudo apt-get install -y haproxy

sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak #open (sudo vi) /etc/haproxy/haproxy.cfg and add the bak files 
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOT
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http-in
    bind *:80
    default_backend webservers

backend webservers
    balance roundrobin
    server web-01 54.81.49.198:80 check
    server web-02 34.226.195.209:80 check
EOT

# Update the hostname with student ID 
sudo hostnamectl set-hostname 654416102-haproxy 

# Enable HAProxy as a service managed by the init script
sudo service haproxy enable 

# Restart HAProxy service
sudo service haproxy restart