#!/usr/bin/env bash
# Install your load balancer

sudo apt-get -y install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-1.8
sudo apt-get update
sudo apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen 5508-webs
    bind *:80
    mode http
    balance roundrobin
    server web-01 34.228.10.0:80 check
    server web-02 3.80.130.8:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart